"""adding bio to user

Revision ID: 543185bd2948
Revises: 02174e97667a
Create Date: 2021-05-01 07:40:44.909578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543185bd2948'
down_revision = '02174e97667a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
